### ISSUE TITLE
MCP3424.cpp  bad two complement implementation.

### ISSUE THREAD

**Issue by miky2k** [bersch/MCP3424#1]
if (cread.srate == SR18B) {
        lval = b2 << 16;
        lval |= b3 << 8 | b4;
        if (lval & 0x800000) lval |= 0xfffc0000;  <-- You need to extend sign value to be 2-complement aritmetic.
    } else {
        lval = (b2 << 8) | b3;
       
        if (lval & 0x8000) lval |= 0xffff0000;    <-- You need to extend sign value to be 2-complement aritmetic.
    }

**Comment by bersch** [comment]
how about this?

`lval = (uint32_t)b2 << 16 | (uint16_t)b3 << 8 | b4;`

**Comment by miky2k** [comment]
Cannot work , does not extend sign.

**Comment by bersch** [comment]
and this?
`    lval =  ~((( b2 & 0x80) << 16 ) - 1 ) // sign`
`              | b2 << 16 | b3 << 8 | b4;`

**Comment by bersch** [comment]
thanks.
